### ISSUE TITLE
Library not showing up

### ISSUE THREAD

**Issue by AbrahamAMartinez** [tkimva/ucr-eecs168#13]
After redoing the NAND section for the third time and it still giving me the same issue I attempted to delete the NAND file and the NAND_testbench file. After doing so myLibrary stopped showing up as a library option.
![screen shot 2016-01-31 at 10 20 46 am](https://cloud.githubusercontent.com/assets/16658134/12703962/e60c59d2-c804-11e5-8dff-715cdc11392e.jpeg)

**Comment by tkimva** [comment]
It seems you deleted either your whole library or just your library link.

If you just deleted library link, then it can be recovered.
You need to add the following line into the file `lib.defs`.

```
DEFINE mylibrary ./myLibrary
```

Then your `libs.defs` should be like the followings:

```
INCLUDE $SAED90_PDK/lib.defs
DEFINE mylibrary ./myLibrary
```

If your design files isn't existed in myLibrary folder, then you cannot recover library with using above solution, then, you need to __redo__ design from scratch again because you accidentally deleted yours. if you want to redo with `myLibrary` name, then you need to physically delete the myLibrary folder. Take a look inside of `myLibrary` folder.

After fixing this, if you still have the same issue, then you still miss some steps and settings from our tutorial for schematic and layout. 

So far, more than 20-30 people already finished and submitted NAND design with only our tutorial-based. So tutorial has no problem.

Your lab is tomorrow, so I can take a look at your problem shortly. Please try to recover your design first as you need to show your design at least to me to get some help.

Good luck

**Comment by tkimva** [comment]
I re-open this issue for others.
